var player = player_trainer_create();
var trainer = mon_create();
	mon_set_seed(trainer, 0, randint());
	repeat (1) mon_level_up(trainer);
	trainer[@ k_mon.hp] = mon_get_max_hp(trainer);
	
	var abilities = trainer[@ k_mon.abilities];
	var aShank = attack_ability_create();
		aShank[@ Ability.Name] = "Shank";
		aShank[@ Ability.RankMask] = 0x0F;
		aShank[@ Ability.TargetField] = FIELD_FOE;
		aShank[@ Ability.TargetMask] = 0x0F;
		aShank[@ AttackAbility.Accuracy] = 90;
	abilities[@ 0] = aShank;
	var aHeal = heal_ability_create();
		aHeal[@ Ability.Name] = "Heal";
		aHeal[@ Ability.RankMask] = 0x0F;//0x08;
		aHeal[@ Ability.TargetField] = FIELD_ALLY;
		aHeal[@ Ability.TargetMask] = 0x0F;
	abilities[@ 1] = aHeal;
	var aCapture = attack_ability_create();
		aCapture[@ Ability.Name] = "Capture";
		aCapture[@ Ability.RankMask] = 0x0F;
		aCapture[@ Ability.TargetField] = FIELD_FOE;
		aCapture[@ Ability.TargetMask] = 0x01;
	abilities[@ 2] = aCapture;
	var aFlee = attack_ability_create();
		aFlee[@ Ability.Name] = "Flee";
		aFlee[@ Ability.RankMask] = 0x0F;
		aFlee[@ Ability.TargetField] = FIELD_FOE;
		aFlee[@ Ability.TargetMask] = 0x0F;
	abilities[@ 3] = aFlee;
ds_list_add(player[k_trainer.party], trainer);
var chimaera = mon_create();
	mon_set_seed(chimaera, 1, randint());
	repeat (3) mon_level_up(chimaera);
	chimaera[@ k_mon.hp] = mon_get_max_hp(chimaera);
	
	var abilities = chimaera[@ k_mon.abilities];
	var aBite = attack_ability_create();
		aBite[@ Ability.Name] = "Bite";
		aBite[@ Ability.RankMask] = 0x03;
		aBite[@ Ability.TargetField] = FIELD_FOE;
		aBite[@ Ability.TargetMask] = 0x01;
		aBite[@ AttackAbility.Accuracy] = 90;
	abilities[@ 0] = aBite;
	var aRush = attack_ability_create();
		aRush[@ Ability.Name] = "Rush";
		aRush[@ Ability.RankMask] = 0x02;
		aRush[@ Ability.TargetField] = FIELD_FOE;
		aRush[@ Ability.TargetMask] = 0x02;
		aRush[@ AttackAbility.Accuracy] = 60;
		aRush[@ AttackAbility.DamageModifier] = 1.5;
	abilities[@ 1] = aRush;
ds_list_add(player[k_trainer.party], chimaera);

var cpu = cpu_trainer_create();
var nix = mon_create();
	mon_set_seed(nix, 2, randint());
	repeat (1) mon_level_up(nix);
	nix[@ k_mon.hp] = mon_get_max_hp(nix);
	
	var abilities = nix[@ k_mon.abilities];
	var aSlash = attack_ability_create();
		aSlash[@ Ability.Name] = "Slash";
		aSlash[@ Ability.RankMask] = 0x03;
		aSlash[@ Ability.TargetField] = FIELD_FOE;
		aSlash[@ Ability.TargetMask] = 0x01;
		aSlash[@ AttackAbility.Accuracy] = 60;
	abilities[@ 0] = aSlash;
ds_list_add(cpu[k_trainer.party], nix);
var nix = mon_create();
	mon_set_seed(nix, 2, randint());
	repeat (1) mon_level_up(nix);
	nix[@ k_mon.hp] = mon_get_max_hp(nix);
	
	var abilities = nix[@ k_mon.abilities];
	var aSlash = attack_ability_create();
		aSlash[@ Ability.Name] = "Slash";
		aSlash[@ Ability.RankMask] = 0x03;
		aSlash[@ Ability.TargetField] = FIELD_FOE;
		aSlash[@ Ability.TargetMask] = 0x01;
		aSlash[@ AttackAbility.Accuracy] = 60;
	abilities[@ 0] = aSlash;
ds_list_add(cpu[k_trainer.party], nix);

var battle = battle_create([player, cpu]);
